name: Labb 3 CI Crazy? I was crazy once... they locked me in a room, a rubber room, a rubber room with rats, and rats make me crazy... Crazy? I was crazy once...

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.pip

      - name: Run tests
        run: |
          cd backend
          pytest
